version: '3.8'

# pma      running at localhost:8080
# roadmap  running at localhost:3000
# api      running at localhost:3030/api/v1/test
# swagger  running at localhost:3030/api/v1/documentation

services:
  front_roadmap:
    image: roadmap_front
    build:
      context: .
      dockerfile: ./Dockerfile_front
    container_name: roadmap_front
    # command: bash -c "chmod 777 -R storage/ && chmod +x composer.load.sh && ./composer.load.sh && php artisan migrate && php-fpm"
    restart: always
    networks:
      - roadmap_dev2
    volumes:
      - ./front:/app
      - ./.env:/app/.env
      - ./api/storage/api-docs:/app/api-docs
    working_dir: /app
    ports:
      - "80:3000"
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - mysql
      - php
    links:
      - mysql
      - php

  mysql:
    image: mysql:8.0
    container_name: roadmap_mysql
    # gera log [Server] Plugin mysql_native_password reported
    # command: --default-authentication-plugin=mysql_native_password
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - "3306:3306"
    networks:
      - roadmap_dev2
    env_file:
      - ./.env
    environment:
      - VIRTUAL_HOST=mysql.roadmap.com
    volumes:
      - ./db-script:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
      - ./mysql.conf:/etc/my.cnf
      # - ./migration:/migration
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      interval: 10s
      retries: 10

  # mysqlinit:
  #   image: mysql:8.0
  #   container_name: roadmap_init
  #   networks:
  #     - roadmap_dev2
  #   env_file:
  #     - ./.env
  #   # volumes:
  #   #   - ./migration:/migration
  #   # command: bash -c "sleep 5 && cd /migration && chmod +x init-db.sh && ./init-db.sh"
  #   depends_on:
  #     - mysql
  #   links:
  #     - mysql

  php:
    image: roadmap_php
    build:
      context: .
      dockerfile: ./Dockerfile_api
    container_name: roadmap_php_fpm
    command: bash -c "chmod 777 -R storage/ && chmod +x composer.load.sh && ./composer.load.sh && php artisan migrate && php-fpm"
    restart: always
    env_file:
      - ./.env
    environment:
      WAIT_HOSTS: mysql:3306
    ports:
      - "9000:9000"
    networks:
      - roadmap_dev2
    volumes:
      - ./api:/www
      - ./api/storage/logs/cron.log:/var/log/cron.log
      - ./.env:/www/.env
    working_dir: /www
    depends_on:
      - mysql
    links:
      - mysql

  api:
    image: nginx:latest
    container_name: roadmap_api_nginx
    restart: always
    ports:
      # - "80:80"
      - "3030:80"
    networks:
      - roadmap_dev2
        # ipv4_address: 172.20.0.6
    env_file:
      - ./.env
    environment:
      - VIRTUAL_HOST=api.roadmap.com
    volumes:
      - ./api:/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php
    extra_hosts:
      - "localhost:172.20.0.6"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: roadmap_pma
    restart: always
    ports:
      - '127.0.0.1:8080:80'
    networks:
      - roadmap_dev2
    environment:
      - PMA_ARBITRARY=1
    links:
      - mysql

volumes:
  mysql_data:

networks:
  roadmap_dev2:
    enable_ipv6: false
    # ipam:
    #   config:
    #     - subnet: 2001:0DB8::/112

secrets:
  db_password:
    file: db_password.txt
  db_user:
    file: db_user.txt