/**
 * Roadmap for Jira API
 * Endpoint mapping for Roadmap for Jira App.
 *
 * OpenAPI spec version: 2.0
 * Contact: contact@mrrafael.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DashParamsModelFilter } from '../models/DashParamsModelFilter';
import { HttpFile } from '../http/http';

export class DashParamsModel {
    'filter': DashParamsModelFilter;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "filter",
            "baseName": "filter",
            "type": "DashParamsModelFilter",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DashParamsModel.attributeTypeMap;
    }

    public constructor() {
    }
}

