/**
 * Roadmap for Jira API
 * Endpoint mapping for Roadmap for Jira App.
 *
 * OpenAPI spec version: 2.0
 * Contact: contact@mrrafael.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProjectConfigModelList } from '../models/ProjectConfigModelList';
import { ProjectConfigModelListListInner } from '../models/ProjectConfigModelListListInner';
import { HttpFile } from '../http/http';

/**
* JSON object containing a list of Projects configs
*/
export class GetProjects200Response {
    'list': Array<ProjectConfigModelListListInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "list",
            "baseName": "list",
            "type": "Array<ProjectConfigModelListListInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetProjects200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

