/**
 * Roadmap for Jira API
 * Endpoint mapping for Roadmap for Jira App.
 *
 * OpenAPI spec version: 2.0
 * Contact: contact@mrrafael.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IssueModel } from '../models/IssueModel';
import { HttpFile } from '../http/http';

export class IssueModelListListInner {
    'keyJira': string;
    'summary': string;
    'status': string;
    'assignee': string;
    'startDate': string;
    'endDate': string;
    'issueType': string;
    'icoUrl': string;
    'issueUrl': string;
    'left': number;
    'top': number;
    'width': number;
    'css': string;
    'exists': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "keyJira",
            "baseName": "keyJira",
            "type": "string",
            "format": ""
        },
        {
            "name": "summary",
            "baseName": "summary",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "assignee",
            "baseName": "assignee",
            "type": "string",
            "format": ""
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "issueType",
            "baseName": "issueType",
            "type": "string",
            "format": ""
        },
        {
            "name": "icoUrl",
            "baseName": "icoUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "issueUrl",
            "baseName": "issueUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "left",
            "baseName": "left",
            "type": "number",
            "format": ""
        },
        {
            "name": "top",
            "baseName": "top",
            "type": "number",
            "format": ""
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number",
            "format": ""
        },
        {
            "name": "css",
            "baseName": "css",
            "type": "string",
            "format": ""
        },
        {
            "name": "exists",
            "baseName": "exists",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IssueModelListListInner.attributeTypeMap;
    }

    public constructor() {
    }
}

