/**
 * Roadmap for Jira API
 * Endpoint mapping for Roadmap for Jira App.
 *
 * OpenAPI spec version: 2.0
 * Contact: contact@mrrafael.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IssueModelListListInner } from '../models/IssueModelListListInner';
import { HttpFile } from '../http/http';

export class IssueModelList {
    'list': Array<IssueModelListListInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "list",
            "baseName": "list",
            "type": "Array<IssueModelListListInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IssueModelList.attributeTypeMap;
    }

    public constructor() {
    }
}

